version: '2'

services:
    postgres:
        image: postgres:10-alpine
        mem_limit: 100M

    php:
        build: .
        environment:
            - PGDATABASE=postgres
            - PGUSER=postgres
            - PGHOST=postgres
        working_dir: /usr/src/app
        volumes:
            - ./:/usr/src/app
        mem_limit: 100M

